### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by toxxn** [spences10/twitter-bot-bootstrap#204]
## Do you want to request a :rocket: _feature_ or report a :bug: _bug_?
bug

### :thinking: Expected Behaviour
The command "npm start" would run correctly.

### :confused: Current Behaviour

ec2-user:~/environment/twitter-bot-bootstrap (master) $ npm start

> twitter-bot-bootstrap@0.2.1 start /home/ec2-user/environment/twitter-bot-bootstrap
> node index.js

 ROFL:ROFL:ROFL:ROFL
         _^___
 L    __/   [] \ 
LOL===__        \     Bot starting...
 L      \________] 
         I   I
       --------/
**/home/ec2-user/environment/twitter-bot-bootstrap/src/helpers/isReply.js:5
    RT.test(tweet.text) ||
                  ^

TypeError: Cannot read property 'text' of undefined**
    at isReply (/home/ec2-user/environment/twitter-bot-bootstrap/src/helpers/isReply.js:5:19)
    at bot.get (/home/ec2-user/environment/twitter-bot-bootstrap/src/api/retweet.js:31:14)
    at /home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:125:13
    at onRequestComplete (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:336:5)
    at Request.<anonymous> (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:348:7)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twitter-bot-bootstrap@0.2.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twitter-bot-bootstrap@0.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-03-21T00_01_19_766Z-debug.log

I had this working earlier today with zeit. I then kept adjusting the code trying to add features, I ended up breaking it to the point it wouldn't run at all. I then created a completely new AWS project. I followed the ReadMe instructions the same as before, and now I am receiving this error which is preventing both "npm start" & "npm run deploy" from working.

Any help would be appreciated!!

thank you!!

**Comment by toxxn** [comment]
I tried reinstalling npm/dependencies and got the following


ec2-user:~/environment/twitter-bot-bootstrap (master) $ npm start

> twitter-bot-bootstrap@0.2.1 start /home/ec2-user/environment/twitter-bot-bootstrap
> node index.js

 ROFL:ROFL:ROFL:ROFL
         _^___
 L    __/   [] \ 
LOL===__        \     Bot starting...
 L      \________] 
         I   I
       --------/
¯_(ツ)_/¯ ERRORDERP: Retweet!
(>ლ) SUCCESS: RT:  https://t.co/tlgrK4t4Mv - tons of snow right now!! #skitahoe #northstarcalifornia #skiheavenly #squawalpine RANDO ID:  6
¯_(ツ)_/¯ ERRORDERP: Cannot Search Tweet!, Description here:  { Error: Query parameters are missing.
    at Object.exports.makeTwitError (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:328:25)
    at Request.<anonymous> (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:348:7)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'Query parameters are missing.',
  code: 25,
  allErrors: [ { code: 25, message: 'Query parameters are missing.' } ],
  twitterReply: { errors: [ [Object] ] },
  statusCode: 400 }
ಠ_ಠ ERRORDERP: Retweet!
ლ(ಠ益ಠლ) SUCCESS: RT:  We found the pot of gold. #StagPartiesTahoe  

#StPatricksDay 

: IG user scrillycheese. 

#TahoeSouth… https://t.co/BFDc5bAUOg RANDO ID:  8
/home/ec2-user/environment/twitter-bot-bootstrap/src/helpers/isReply.js:5
    RT.test(tweet.text) ||
                  ^

TypeError: Cannot read property 'text' of undefined
    at isReply (/home/ec2-user/environment/twitter-bot-bootstrap/src/helpers/isReply.js:5:19)
    at bot.get (/home/ec2-user/environment/twitter-bot-bootstrap/src/api/retweet.js:31:14)
    at /home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:125:13
    at onRequestComplete (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:336:5)
    at Request.<anonymous> (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:348:7)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twitter-bot-bootstrap@0.2.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twitter-bot-bootstrap@0.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-03-21T00_11_15_215Z-debug.log

###
I then thought maybe i had an extra at the end of my query parameters which was causing this, and removed that, but i am continuing to get this error no matter how I adjust the query parameters.


ec2-user:~/environment/twitter-bot-bootstrap (master) $ npm start

> twitter-bot-bootstrap@0.2.1 start /home/ec2-user/environment/twitter-bot-bootstrap
> node index.js

 ROFL:ROFL:ROFL:ROFL
         _^___
 L    __/   [] \ 
LOL===__        \     Bot starting...
 L      \________] 
         I   I
       --------/
ʕʘ̅͜ʘ̅ʔ ERRORDERP: Retweet!
ಠ_ಠ SUCCESS: RT:  We found the pot of gold. #StagPartiesTahoe  

#StPatricksDay 

: IG user scrillycheese. 

#TahoeSouth… https://t.co/BFDc5bAUOg RANDO ID:  8
/home/ec2-user/environment/twitter-bot-bootstrap/src/helpers/isReply.js:5
    RT.test(tweet.text) ||
                  ^

TypeError: Cannot read property 'text' of undefined
    at isReply (/home/ec2-user/environment/twitter-bot-bootstrap/src/helpers/isReply.js:5:19)
    at bot.get (/home/ec2-user/environment/twitter-bot-bootstrap/src/api/retweet.js:31:14)
    at /home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:125:13
    at onRequestComplete (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:336:5)
    at Request.<anonymous> (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/twit/lib/twitter.js:348:7)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (/home/ec2-user/environment/twitter-bot-bootstrap/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Gunzip.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twitter-bot-bootstrap@0.2.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twitter-bot-bootstrap@0.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-03-21T00_18_33_078Z-debug.log

**Comment by toxxn** [comment]
I think this may be a problem with my query strings... If I adjust the query string to have too many minuses after a hashtag, it seems it wont run. However if I have a list of separate "1 hashtag and 1 minus", the code works.

Is there a way to blacklist certain phrases and hashtags?

**Comment by spences10** [comment]
Hey @toxxn take a look at #127 for how to implement a blacklist and feel free to make a PR if you get it working 👍

Closing this as it appears to be your querys causing the issue

Thanks
