### ISSUE TITLE
Bad request on start

### ISSUE THREAD

**Issue by danielfeloiola** [spences10/twitter-bot-bootstrap#249]
### :thinking: Expected Behaviour
Bot start working

### :confused: Current Behaviour
Bad request (410)
Any ideas on how to fix this? Is it gone forever?

Log:
> twitter-bot-bootstrap@0.2.1 start /home/ubuntu/workspace/twitter-bot-bootstrap
> node index.js

 ROFL:ROFL:ROFL:ROFL
         _^___
 L    __/   [] \ 
LOL===__        \     Bot starting...
 L      \________] 
         I   I
       --------/
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Bad Twitter streaming request: 410
    at Object.exports.makeTwitError (/home/ubuntu/workspace/twitter-bot-bootstrap/node_modules/twit/lib/helpers.js:74:13)
    at Request.<anonymous> (/home/ubuntu/workspace/twitter-bot-bootstrap/node_modules/twit/lib/streaming-api-connection.js:96:29)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/workspace/twitter-bot-bootstrap/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twitter-bot-bootstrap@0.2.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twitter-bot-bootstrap@0.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-11-02T20_39_35_257Z-debug.log

**Comment by spences10** [comment]
Hey @danielfeloiola take a look at using https://github.com/spences10/delay-tweet 

This project is dated and I'm not sure if it is still functioning.

Delay tweet was the last Twitter project I worked on, due to changes in the Twitter API they may both be broken.

**Comment by TheeMattOliver** [comment]
We're getting the "Error: Bad Twitter streaming request: 410"  because the stream API endpoint has been closed.

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746

They recommend migrating to the "Account Activity API".

I'd love it if @spences10 was planning a fix!

**Comment by spences10** [comment]
Thanks for clearing that up @theemattoliver
